// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCom_ListNodeOfListOfDocument.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCom_Document_HeaderFile
#include <McCadCom_Document.hxx>
#endif
#ifndef _McCadCom_ListOfDocument_HeaderFile
#include <McCadCom_ListOfDocument.hxx>
#endif
#ifndef _McCadCom_ListIteratorOfListOfDocument_HeaderFile
#include <McCadCom_ListIteratorOfListOfDocument.hxx>
#endif
//McCadCom_ListNodeOfListOfDocument::~McCadCom_ListNodeOfListOfDocument() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCom_ListNodeOfListOfDocument_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCom_ListNodeOfListOfDocument",
			                                 sizeof(McCadCom_ListNodeOfListOfDocument),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCom_ListNodeOfListOfDocument) Handle(McCadCom_ListNodeOfListOfDocument)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCom_ListNodeOfListOfDocument) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCom_ListNodeOfListOfDocument))) {
       _anOtherObject = Handle(McCadCom_ListNodeOfListOfDocument)((Handle(McCadCom_ListNodeOfListOfDocument)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCom_ListNodeOfListOfDocument::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCom_ListNodeOfListOfDocument) ; 
}
//Standard_Boolean McCadCom_ListNodeOfListOfDocument::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCom_ListNodeOfListOfDocument) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadCom_ListNodeOfListOfDocument::~Handle_McCadCom_ListNodeOfListOfDocument() {}
#define Item Handle_McCadCom_Document
#define Item_hxx <McCadCom_Document.hxx>
#define TCollection_ListNode McCadCom_ListNodeOfListOfDocument
#define TCollection_ListNode_hxx <McCadCom_ListNodeOfListOfDocument.hxx>
#define TCollection_ListIterator McCadCom_ListIteratorOfListOfDocument
#define TCollection_ListIterator_hxx <McCadCom_ListIteratorOfListOfDocument.hxx>
#define Handle_TCollection_ListNode Handle_McCadCom_ListNodeOfListOfDocument
#define TCollection_ListNode_Type_() McCadCom_ListNodeOfListOfDocument_Type_()
#define TCollection_List McCadCom_ListOfDocument
#define TCollection_List_hxx <McCadCom_ListOfDocument.hxx>
#include <TCollection_ListNode.gxx>

