// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCom_StdMapNodeOfMapOfView.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCom_View_HeaderFile
#include <McCadCom_View.hxx>
#endif
#ifndef _TColStd_MapTransientHasher_HeaderFile
#include <TColStd_MapTransientHasher.hxx>
#endif
#ifndef _McCadCom_MapOfView_HeaderFile
#include <McCadCom_MapOfView.hxx>
#endif
#ifndef _McCadCom_MapIteratorOfMapOfView_HeaderFile
#include <McCadCom_MapIteratorOfMapOfView.hxx>
#endif
//McCadCom_StdMapNodeOfMapOfView::~McCadCom_StdMapNodeOfMapOfView() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCom_StdMapNodeOfMapOfView_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCom_StdMapNodeOfMapOfView",
			                                 sizeof(McCadCom_StdMapNodeOfMapOfView),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCom_StdMapNodeOfMapOfView) Handle(McCadCom_StdMapNodeOfMapOfView)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCom_StdMapNodeOfMapOfView) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCom_StdMapNodeOfMapOfView))) {
       _anOtherObject = Handle(McCadCom_StdMapNodeOfMapOfView)((Handle(McCadCom_StdMapNodeOfMapOfView)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCom_StdMapNodeOfMapOfView::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCom_StdMapNodeOfMapOfView) ; 
}
//Standard_Boolean McCadCom_StdMapNodeOfMapOfView::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCom_StdMapNodeOfMapOfView) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadCom_StdMapNodeOfMapOfView::~Handle_McCadCom_StdMapNodeOfMapOfView() {}
#define TheKey Handle_McCadCom_View
#define TheKey_hxx <McCadCom_View.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <TColStd_MapTransientHasher.hxx>
#define TCollection_StdMapNode McCadCom_StdMapNodeOfMapOfView
#define TCollection_StdMapNode_hxx <McCadCom_StdMapNodeOfMapOfView.hxx>
#define TCollection_MapIterator McCadCom_MapIteratorOfMapOfView
#define TCollection_MapIterator_hxx <McCadCom_MapIteratorOfMapOfView.hxx>
#define Handle_TCollection_StdMapNode Handle_McCadCom_StdMapNodeOfMapOfView
#define TCollection_StdMapNode_Type_() McCadCom_StdMapNodeOfMapOfView_Type_()
#define TCollection_Map McCadCom_MapOfView
#define TCollection_Map_hxx <McCadCom_MapOfView.hxx>
#include <TCollection_StdMapNode.gxx>

