// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCom_SequenceNodeOfSequenceOfCasView.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCom_CasView_HeaderFile
#include <McCadCom_CasView.hxx>
#endif
#ifndef _McCadCom_SequenceOfCasView_HeaderFile
#include <McCadCom_SequenceOfCasView.hxx>
#endif
//McCadCom_SequenceNodeOfSequenceOfCasView::~McCadCom_SequenceNodeOfSequenceOfCasView() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCom_SequenceNodeOfSequenceOfCasView_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_SeqNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCom_SequenceNodeOfSequenceOfCasView",
			                                 sizeof(McCadCom_SequenceNodeOfSequenceOfCasView),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCom_SequenceNodeOfSequenceOfCasView) Handle(McCadCom_SequenceNodeOfSequenceOfCasView)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCom_SequenceNodeOfSequenceOfCasView) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCom_SequenceNodeOfSequenceOfCasView))) {
       _anOtherObject = Handle(McCadCom_SequenceNodeOfSequenceOfCasView)((Handle(McCadCom_SequenceNodeOfSequenceOfCasView)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCom_SequenceNodeOfSequenceOfCasView::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCom_SequenceNodeOfSequenceOfCasView) ; 
}
//Standard_Boolean McCadCom_SequenceNodeOfSequenceOfCasView::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCom_SequenceNodeOfSequenceOfCasView) == AType || TCollection_SeqNode::IsKind(AType)); 
//}
//Handle_McCadCom_SequenceNodeOfSequenceOfCasView::~Handle_McCadCom_SequenceNodeOfSequenceOfCasView() {}
#define SeqItem Handle_McCadCom_CasView
#define SeqItem_hxx <McCadCom_CasView.hxx>
#define TCollection_SequenceNode McCadCom_SequenceNodeOfSequenceOfCasView
#define TCollection_SequenceNode_hxx <McCadCom_SequenceNodeOfSequenceOfCasView.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadCom_SequenceNodeOfSequenceOfCasView
#define TCollection_SequenceNode_Type_() McCadCom_SequenceNodeOfSequenceOfCasView_Type_()
#define TCollection_Sequence McCadCom_SequenceOfCasView
#define TCollection_Sequence_hxx <McCadCom_SequenceOfCasView.hxx>
#include <TCollection_SequenceNode.gxx>

