// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCom_ListOfCasView.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _McCadCom_ListIteratorOfListOfCasView_HeaderFile
#include <McCadCom_ListIteratorOfListOfCasView.hxx>
#endif
#ifndef _McCadCom_CasView_HeaderFile
#include <McCadCom_CasView.hxx>
#endif
#ifndef _McCadCom_ListNodeOfListOfCasView_HeaderFile
#include <McCadCom_ListNodeOfListOfCasView.hxx>
#endif
 

#define Item Handle_McCadCom_CasView
#define Item_hxx <McCadCom_CasView.hxx>
#define TCollection_ListNode McCadCom_ListNodeOfListOfCasView
#define TCollection_ListNode_hxx <McCadCom_ListNodeOfListOfCasView.hxx>
#define TCollection_ListIterator McCadCom_ListIteratorOfListOfCasView
#define TCollection_ListIterator_hxx <McCadCom_ListIteratorOfListOfCasView.hxx>
#define Handle_TCollection_ListNode Handle_McCadCom_ListNodeOfListOfCasView
#define TCollection_ListNode_Type_() McCadCom_ListNodeOfListOfCasView_Type_()
#define TCollection_List McCadCom_ListOfCasView
#define TCollection_List_hxx <McCadCom_ListOfCasView.hxx>
#include <TCollection_List.gxx>

