// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCom_ListNodeOfListOfView.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCom_View_HeaderFile
#include <McCadCom_View.hxx>
#endif
#ifndef _McCadCom_ListOfView_HeaderFile
#include <McCadCom_ListOfView.hxx>
#endif
#ifndef _McCadCom_ListIteratorOfListOfView_HeaderFile
#include <McCadCom_ListIteratorOfListOfView.hxx>
#endif
//McCadCom_ListNodeOfListOfView::~McCadCom_ListNodeOfListOfView() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCom_ListNodeOfListOfView_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCom_ListNodeOfListOfView",
			                                 sizeof(McCadCom_ListNodeOfListOfView),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCom_ListNodeOfListOfView) Handle(McCadCom_ListNodeOfListOfView)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCom_ListNodeOfListOfView) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCom_ListNodeOfListOfView))) {
       _anOtherObject = Handle(McCadCom_ListNodeOfListOfView)((Handle(McCadCom_ListNodeOfListOfView)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCom_ListNodeOfListOfView::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCom_ListNodeOfListOfView) ; 
}
//Standard_Boolean McCadCom_ListNodeOfListOfView::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCom_ListNodeOfListOfView) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadCom_ListNodeOfListOfView::~Handle_McCadCom_ListNodeOfListOfView() {}
#define Item Handle_McCadCom_View
#define Item_hxx <McCadCom_View.hxx>
#define TCollection_ListNode McCadCom_ListNodeOfListOfView
#define TCollection_ListNode_hxx <McCadCom_ListNodeOfListOfView.hxx>
#define TCollection_ListIterator McCadCom_ListIteratorOfListOfView
#define TCollection_ListIterator_hxx <McCadCom_ListIteratorOfListOfView.hxx>
#define Handle_TCollection_ListNode Handle_McCadCom_ListNodeOfListOfView
#define TCollection_ListNode_Type_() McCadCom_ListNodeOfListOfView_Type_()
#define TCollection_List McCadCom_ListOfView
#define TCollection_List_hxx <McCadCom_ListOfView.hxx>
#include <TCollection_ListNode.gxx>

