// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadMcRead_DataMapNodeOfDataMapOfIntegerFill.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadMcRead_Fill_HeaderFile
#include <McCadMcRead_Fill.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadMcRead_DataMapOfIntegerFill_HeaderFile
#include <McCadMcRead_DataMapOfIntegerFill.hxx>
#endif
#ifndef _McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill_HeaderFile
#include <McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill.hxx>
#endif
//McCadMcRead_DataMapNodeOfDataMapOfIntegerFill::~McCadMcRead_DataMapNodeOfDataMapOfIntegerFill() {}
 


Standard_EXPORT Handle_Standard_Type& McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadMcRead_DataMapNodeOfDataMapOfIntegerFill",
			                                 sizeof(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill) Handle(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill))) {
       _anOtherObject = Handle(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill)((Handle(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadMcRead_DataMapNodeOfDataMapOfIntegerFill::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill) ; 
}
//Standard_Boolean McCadMcRead_DataMapNodeOfDataMapOfIntegerFill::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadMcRead_DataMapNodeOfDataMapOfIntegerFill) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill::~Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill() {}
#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadMcRead_Fill
#define TheItem_hxx <McCadMcRead_Fill.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadMcRead_DataMapNodeOfDataMapOfIntegerFill
#define TCollection_DataMapNode_hxx <McCadMcRead_DataMapNodeOfDataMapOfIntegerFill.hxx>
#define TCollection_DataMapIterator McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill
#define TCollection_DataMapIterator_hxx <McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill
#define TCollection_DataMapNode_Type_() McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_Type_()
#define TCollection_DataMap McCadMcRead_DataMapOfIntegerFill
#define TCollection_DataMap_hxx <McCadMcRead_DataMapOfIntegerFill.hxx>
#include <TCollection_DataMapNode.gxx>

