// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadTDS_DataMapNodeOfDataMapOfIntegerSolid.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadTDS_ExtSolid_HeaderFile
#include <McCadTDS_ExtSolid.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadTDS_DataMapOfIntegerSolid_HeaderFile
#include <McCadTDS_DataMapOfIntegerSolid.hxx>
#endif
#ifndef _McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid_HeaderFile
#include <McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid.hxx>
#endif
//McCadTDS_DataMapNodeOfDataMapOfIntegerSolid::~McCadTDS_DataMapNodeOfDataMapOfIntegerSolid() {}
 


Standard_EXPORT Handle_Standard_Type& McCadTDS_DataMapNodeOfDataMapOfIntegerSolid_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadTDS_DataMapNodeOfDataMapOfIntegerSolid",
			                                 sizeof(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid) Handle(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid))) {
       _anOtherObject = Handle(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid)((Handle(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadTDS_DataMapNodeOfDataMapOfIntegerSolid::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid) ; 
}
//Standard_Boolean McCadTDS_DataMapNodeOfDataMapOfIntegerSolid::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadTDS_DataMapNodeOfDataMapOfIntegerSolid) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadTDS_DataMapNodeOfDataMapOfIntegerSolid::~Handle_McCadTDS_DataMapNodeOfDataMapOfIntegerSolid() {}
#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadTDS_ExtSolid
#define TheItem_hxx <McCadTDS_ExtSolid.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadTDS_DataMapNodeOfDataMapOfIntegerSolid
#define TCollection_DataMapNode_hxx <McCadTDS_DataMapNodeOfDataMapOfIntegerSolid.hxx>
#define TCollection_DataMapIterator McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid
#define TCollection_DataMapIterator_hxx <McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadTDS_DataMapNodeOfDataMapOfIntegerSolid
#define TCollection_DataMapNode_Type_() McCadTDS_DataMapNodeOfDataMapOfIntegerSolid_Type_()
#define TCollection_DataMap McCadTDS_DataMapOfIntegerSolid
#define TCollection_DataMap_hxx <McCadTDS_DataMapOfIntegerSolid.hxx>
#include <TCollection_DataMapNode.gxx>

