// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadTDS_DataMapOfIntegerSolid.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _McCadTDS_ExtSolid_HeaderFile
#include <McCadTDS_ExtSolid.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadTDS_DataMapNodeOfDataMapOfIntegerSolid_HeaderFile
#include <McCadTDS_DataMapNodeOfDataMapOfIntegerSolid.hxx>
#endif
#ifndef _McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid_HeaderFile
#include <McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid.hxx>
#endif
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadTDS_ExtSolid
#define TheItem_hxx <McCadTDS_ExtSolid.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadTDS_DataMapNodeOfDataMapOfIntegerSolid
#define TCollection_DataMapNode_hxx <McCadTDS_DataMapNodeOfDataMapOfIntegerSolid.hxx>
#define TCollection_DataMapIterator McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid
#define TCollection_DataMapIterator_hxx <McCadTDS_DataMapIteratorOfDataMapOfIntegerSolid.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadTDS_DataMapNodeOfDataMapOfIntegerSolid
#define TCollection_DataMapNode_Type_() McCadTDS_DataMapNodeOfDataMapOfIntegerSolid_Type_()
#define TCollection_DataMap McCadTDS_DataMapOfIntegerSolid
#define TCollection_DataMap_hxx <McCadTDS_DataMapOfIntegerSolid.hxx>
#include <TCollection_DataMap.gxx>

