// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadMDReader_DataMapIteratorOfDataMapOfAsciiStringAsciiString.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _McCadMDReader_MapAsciiStringHasher_HeaderFile
#include <McCadMDReader_MapAsciiStringHasher.hxx>
#endif
#ifndef _McCadMDReader_DataMapOfAsciiStringAsciiString_HeaderFile
#include <McCadMDReader_DataMapOfAsciiStringAsciiString.hxx>
#endif
#ifndef _McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString_HeaderFile
#include <McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString.hxx>
#endif
 

#define TheKey TCollection_AsciiString
#define TheKey_hxx <TCollection_AsciiString.hxx>
#define TheItem TCollection_AsciiString
#define TheItem_hxx <TCollection_AsciiString.hxx>
#define Hasher McCadMDReader_MapAsciiStringHasher
#define Hasher_hxx <McCadMDReader_MapAsciiStringHasher.hxx>
#define TCollection_DataMapNode McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString
#define TCollection_DataMapNode_hxx <McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString.hxx>
#define TCollection_DataMapIterator McCadMDReader_DataMapIteratorOfDataMapOfAsciiStringAsciiString
#define TCollection_DataMapIterator_hxx <McCadMDReader_DataMapIteratorOfDataMapOfAsciiStringAsciiString.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString
#define TCollection_DataMapNode_Type_() McCadMDReader_DataMapNodeOfDataMapOfAsciiStringAsciiString_Type_()
#define TCollection_DataMap McCadMDReader_DataMapOfAsciiStringAsciiString
#define TCollection_DataMap_hxx <McCadMDReader_DataMapOfAsciiStringAsciiString.hxx>
#include <TCollection_DataMapIterator.gxx>

