// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadDiscDs_HSequenceOfDiscFace.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _McCadDiscDs_DiscFace_HeaderFile
#include <McCadDiscDs_DiscFace.hxx>
#endif
#ifndef _McCadDiscDs_SequenceOfDiscFace_HeaderFile
#include <McCadDiscDs_SequenceOfDiscFace.hxx>
#endif
//McCadDiscDs_HSequenceOfDiscFace::~McCadDiscDs_HSequenceOfDiscFace() {}
 


Standard_EXPORT Handle_Standard_Type& McCadDiscDs_HSequenceOfDiscFace_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadDiscDs_HSequenceOfDiscFace",
			                                 sizeof(McCadDiscDs_HSequenceOfDiscFace),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadDiscDs_HSequenceOfDiscFace) Handle(McCadDiscDs_HSequenceOfDiscFace)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadDiscDs_HSequenceOfDiscFace) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadDiscDs_HSequenceOfDiscFace))) {
       _anOtherObject = Handle(McCadDiscDs_HSequenceOfDiscFace)((Handle(McCadDiscDs_HSequenceOfDiscFace)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadDiscDs_HSequenceOfDiscFace::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadDiscDs_HSequenceOfDiscFace) ; 
}
//Standard_Boolean McCadDiscDs_HSequenceOfDiscFace::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadDiscDs_HSequenceOfDiscFace) == AType || MMgt_TShared::IsKind(AType)); 
//}
//Handle_McCadDiscDs_HSequenceOfDiscFace::~Handle_McCadDiscDs_HSequenceOfDiscFace() {}
#define Item McCadDiscDs_DiscFace
#define Item_hxx <McCadDiscDs_DiscFace.hxx>
#define TheSequence McCadDiscDs_SequenceOfDiscFace
#define TheSequence_hxx <McCadDiscDs_SequenceOfDiscFace.hxx>
#define TCollection_HSequence McCadDiscDs_HSequenceOfDiscFace
#define TCollection_HSequence_hxx <McCadDiscDs_HSequenceOfDiscFace.hxx>
#define Handle_TCollection_HSequence Handle_McCadDiscDs_HSequenceOfDiscFace
#define TCollection_HSequence_Type_() McCadDiscDs_HSequenceOfDiscFace_Type_()
#include <TCollection_HSequence.gxx>

