// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadDiscDs_ListNodeOfListOfDiscFace.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadDiscDs_DiscFace_HeaderFile
#include <McCadDiscDs_DiscFace.hxx>
#endif
#ifndef _McCadDiscDs_ListOfDiscFace_HeaderFile
#include <McCadDiscDs_ListOfDiscFace.hxx>
#endif
#ifndef _McCadDiscDs_ListIteratorOfListOfDiscFace_HeaderFile
#include <McCadDiscDs_ListIteratorOfListOfDiscFace.hxx>
#endif
//McCadDiscDs_ListNodeOfListOfDiscFace::~McCadDiscDs_ListNodeOfListOfDiscFace() {}
 


Standard_EXPORT Handle_Standard_Type& McCadDiscDs_ListNodeOfListOfDiscFace_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadDiscDs_ListNodeOfListOfDiscFace",
			                                 sizeof(McCadDiscDs_ListNodeOfListOfDiscFace),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadDiscDs_ListNodeOfListOfDiscFace) Handle(McCadDiscDs_ListNodeOfListOfDiscFace)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadDiscDs_ListNodeOfListOfDiscFace) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadDiscDs_ListNodeOfListOfDiscFace))) {
       _anOtherObject = Handle(McCadDiscDs_ListNodeOfListOfDiscFace)((Handle(McCadDiscDs_ListNodeOfListOfDiscFace)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadDiscDs_ListNodeOfListOfDiscFace::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadDiscDs_ListNodeOfListOfDiscFace) ; 
}
//Standard_Boolean McCadDiscDs_ListNodeOfListOfDiscFace::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadDiscDs_ListNodeOfListOfDiscFace) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadDiscDs_ListNodeOfListOfDiscFace::~Handle_McCadDiscDs_ListNodeOfListOfDiscFace() {}
#define Item McCadDiscDs_DiscFace
#define Item_hxx <McCadDiscDs_DiscFace.hxx>
#define TCollection_ListNode McCadDiscDs_ListNodeOfListOfDiscFace
#define TCollection_ListNode_hxx <McCadDiscDs_ListNodeOfListOfDiscFace.hxx>
#define TCollection_ListIterator McCadDiscDs_ListIteratorOfListOfDiscFace
#define TCollection_ListIterator_hxx <McCadDiscDs_ListIteratorOfListOfDiscFace.hxx>
#define Handle_TCollection_ListNode Handle_McCadDiscDs_ListNodeOfListOfDiscFace
#define TCollection_ListNode_Type_() McCadDiscDs_ListNodeOfListOfDiscFace_Type_()
#define TCollection_List McCadDiscDs_ListOfDiscFace
#define TCollection_List_hxx <McCadDiscDs_ListOfDiscFace.hxx>
#include <TCollection_ListNode.gxx>

