// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCSGGeom_Cell_HeaderFile
#include <McCadCSGGeom_Cell.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapOfIntegerCell_HeaderFile
#include <McCadCSGGeom_DataMapOfIntegerCell.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerCell_HeaderFile
#include <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerCell.hxx>
#endif
//McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell::~McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell",
			                                 sizeof(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell) Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell))) {
       _anOtherObject = Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell)((Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell) ; 
}
//Standard_Boolean McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell::~Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell() {}
#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadCSGGeom_Cell
#define TheItem_hxx <McCadCSGGeom_Cell.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell
#define TCollection_DataMapNode_hxx <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell.hxx>
#define TCollection_DataMapIterator McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerCell
#define TCollection_DataMapIterator_hxx <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerCell.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell
#define TCollection_DataMapNode_Type_() McCadCSGGeom_DataMapNodeOfDataMapOfIntegerCell_Type_()
#define TCollection_DataMap McCadCSGGeom_DataMapOfIntegerCell
#define TCollection_DataMap_hxx <McCadCSGGeom_DataMapOfIntegerCell.hxx>
#include <TCollection_DataMapNode.gxx>

