// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCSGGeom_HSequenceOfTransformation.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _McCadCSGGeom_Transformation_HeaderFile
#include <McCadCSGGeom_Transformation.hxx>
#endif
#ifndef _McCadCSGGeom_SequenceOfTransformation_HeaderFile
#include <McCadCSGGeom_SequenceOfTransformation.hxx>
#endif
//McCadCSGGeom_HSequenceOfTransformation::~McCadCSGGeom_HSequenceOfTransformation() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCSGGeom_HSequenceOfTransformation_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCSGGeom_HSequenceOfTransformation",
			                                 sizeof(McCadCSGGeom_HSequenceOfTransformation),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCSGGeom_HSequenceOfTransformation) Handle(McCadCSGGeom_HSequenceOfTransformation)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCSGGeom_HSequenceOfTransformation) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCSGGeom_HSequenceOfTransformation))) {
       _anOtherObject = Handle(McCadCSGGeom_HSequenceOfTransformation)((Handle(McCadCSGGeom_HSequenceOfTransformation)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCSGGeom_HSequenceOfTransformation::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCSGGeom_HSequenceOfTransformation) ; 
}
//Standard_Boolean McCadCSGGeom_HSequenceOfTransformation::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCSGGeom_HSequenceOfTransformation) == AType || MMgt_TShared::IsKind(AType)); 
//}
//Handle_McCadCSGGeom_HSequenceOfTransformation::~Handle_McCadCSGGeom_HSequenceOfTransformation() {}
#define Item Handle_McCadCSGGeom_Transformation
#define Item_hxx <McCadCSGGeom_Transformation.hxx>
#define TheSequence McCadCSGGeom_SequenceOfTransformation
#define TheSequence_hxx <McCadCSGGeom_SequenceOfTransformation.hxx>
#define TCollection_HSequence McCadCSGGeom_HSequenceOfTransformation
#define TCollection_HSequence_hxx <McCadCSGGeom_HSequenceOfTransformation.hxx>
#define Handle_TCollection_HSequence Handle_McCadCSGGeom_HSequenceOfTransformation
#define TCollection_HSequence_Type_() McCadCSGGeom_HSequenceOfTransformation_Type_()
#include <TCollection_HSequence.gxx>

