// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCSGGeom_Transformation_HeaderFile
#include <McCadCSGGeom_Transformation.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapOfIntegerTransformation_HeaderFile
#include <McCadCSGGeom_DataMapOfIntegerTransformation.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerTransformation_HeaderFile
#include <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerTransformation.hxx>
#endif
//McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation::~McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation",
			                                 sizeof(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation) Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation))) {
       _anOtherObject = Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation)((Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation) ; 
}
//Standard_Boolean McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation::~Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation() {}
#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadCSGGeom_Transformation
#define TheItem_hxx <McCadCSGGeom_Transformation.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation
#define TCollection_DataMapNode_hxx <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation.hxx>
#define TCollection_DataMapIterator McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerTransformation
#define TCollection_DataMapIterator_hxx <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerTransformation.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation
#define TCollection_DataMapNode_Type_() McCadCSGGeom_DataMapNodeOfDataMapOfIntegerTransformation_Type_()
#define TCollection_DataMap McCadCSGGeom_DataMapOfIntegerTransformation
#define TCollection_DataMap_hxx <McCadCSGGeom_DataMapOfIntegerTransformation.hxx>
#include <TCollection_DataMapNode.gxx>

