// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCSGGeom_SequenceNodeOfSequenceOfSurface.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadCSGGeom_Surface_HeaderFile
#include <McCadCSGGeom_Surface.hxx>
#endif
#ifndef _McCadCSGGeom_SequenceOfSurface_HeaderFile
#include <McCadCSGGeom_SequenceOfSurface.hxx>
#endif
//McCadCSGGeom_SequenceNodeOfSequenceOfSurface::~McCadCSGGeom_SequenceNodeOfSequenceOfSurface() {}
 


Standard_EXPORT Handle_Standard_Type& McCadCSGGeom_SequenceNodeOfSequenceOfSurface_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_SeqNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadCSGGeom_SequenceNodeOfSequenceOfSurface",
			                                 sizeof(McCadCSGGeom_SequenceNodeOfSequenceOfSurface),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadCSGGeom_SequenceNodeOfSequenceOfSurface) Handle(McCadCSGGeom_SequenceNodeOfSequenceOfSurface)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadCSGGeom_SequenceNodeOfSequenceOfSurface) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadCSGGeom_SequenceNodeOfSequenceOfSurface))) {
       _anOtherObject = Handle(McCadCSGGeom_SequenceNodeOfSequenceOfSurface)((Handle(McCadCSGGeom_SequenceNodeOfSequenceOfSurface)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadCSGGeom_SequenceNodeOfSequenceOfSurface::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadCSGGeom_SequenceNodeOfSequenceOfSurface) ; 
}
//Standard_Boolean McCadCSGGeom_SequenceNodeOfSequenceOfSurface::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadCSGGeom_SequenceNodeOfSequenceOfSurface) == AType || TCollection_SeqNode::IsKind(AType)); 
//}
//Handle_McCadCSGGeom_SequenceNodeOfSequenceOfSurface::~Handle_McCadCSGGeom_SequenceNodeOfSequenceOfSurface() {}
#define SeqItem Handle_McCadCSGGeom_Surface
#define SeqItem_hxx <McCadCSGGeom_Surface.hxx>
#define TCollection_SequenceNode McCadCSGGeom_SequenceNodeOfSequenceOfSurface
#define TCollection_SequenceNode_hxx <McCadCSGGeom_SequenceNodeOfSequenceOfSurface.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadCSGGeom_SequenceNodeOfSequenceOfSurface
#define TCollection_SequenceNode_Type_() McCadCSGGeom_SequenceNodeOfSequenceOfSurface_Type_()
#define TCollection_Sequence McCadCSGGeom_SequenceOfSurface
#define TCollection_Sequence_hxx <McCadCSGGeom_SequenceOfSurface.hxx>
#include <TCollection_SequenceNode.gxx>

