// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerSurface.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _McCadCSGGeom_Surface_HeaderFile
#include <McCadCSGGeom_Surface.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapOfIntegerSurface_HeaderFile
#include <McCadCSGGeom_DataMapOfIntegerSurface.hxx>
#endif
#ifndef _McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface_HeaderFile
#include <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface.hxx>
#endif
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadCSGGeom_Surface
#define TheItem_hxx <McCadCSGGeom_Surface.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface
#define TCollection_DataMapNode_hxx <McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface.hxx>
#define TCollection_DataMapIterator McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerSurface
#define TCollection_DataMapIterator_hxx <McCadCSGGeom_DataMapIteratorOfDataMapOfIntegerSurface.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface
#define TCollection_DataMapNode_Type_() McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface_Type_()
#define TCollection_DataMap McCadCSGGeom_DataMapOfIntegerSurface
#define TCollection_DataMap_hxx <McCadCSGGeom_DataMapOfIntegerSurface.hxx>
#include <TCollection_DataMapIterator.gxx>

