// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadAEV_ListNodeOfListOfViewer.hxx>

#ifndef _Standard_TypeMismatch_HeaderFile
#include <Standard_TypeMismatch.hxx>
#endif

#ifndef _McCadAEV_Viewer_HeaderFile
#include <McCadAEV_Viewer.hxx>
#endif
#ifndef _McCadAEV_ListOfViewer_HeaderFile
#include <McCadAEV_ListOfViewer.hxx>
#endif
#ifndef _McCadAEV_ListIteratorOfListOfViewer_HeaderFile
#include <McCadAEV_ListIteratorOfListOfViewer.hxx>
#endif
//McCadAEV_ListNodeOfListOfViewer::~McCadAEV_ListNodeOfListOfViewer() {}
 


Standard_EXPORT Handle_Standard_Type& McCadAEV_ListNodeOfListOfViewer_Type_()
{

    static Handle_Standard_Type aType1 = STANDARD_TYPE(TCollection_MapNode);
  static Handle_Standard_Type aType2 = STANDARD_TYPE(MMgt_TShared);
  static Handle_Standard_Type aType3 = STANDARD_TYPE(Standard_Transient);
 

  static Handle_Standard_Transient _Ancestors[]= {aType1,aType2,aType3,NULL};
  static Handle_Standard_Type _aType = new Standard_Type("McCadAEV_ListNodeOfListOfViewer",
			                                 sizeof(McCadAEV_ListNodeOfListOfViewer),
			                                 1,
			                                 (Standard_Address)_Ancestors,
			                                 (Standard_Address)NULL);

  return _aType;
}


// DownCast method
//   allow safe downcasting
//
const Handle(McCadAEV_ListNodeOfListOfViewer) Handle(McCadAEV_ListNodeOfListOfViewer)::DownCast(const Handle(Standard_Transient)& AnObject) 
{
  Handle(McCadAEV_ListNodeOfListOfViewer) _anOtherObject;

  if (!AnObject.IsNull()) {
     if (AnObject->IsKind(STANDARD_TYPE(McCadAEV_ListNodeOfListOfViewer))) {
       _anOtherObject = Handle(McCadAEV_ListNodeOfListOfViewer)((Handle(McCadAEV_ListNodeOfListOfViewer)&)AnObject);
     }
  }

  return _anOtherObject ;
}
const Handle(Standard_Type)& McCadAEV_ListNodeOfListOfViewer::DynamicType() const 
{ 
  return STANDARD_TYPE(McCadAEV_ListNodeOfListOfViewer) ; 
}
//Standard_Boolean McCadAEV_ListNodeOfListOfViewer::IsKind(const Handle(Standard_Type)& AType) const 
//{ 
//  return (STANDARD_TYPE(McCadAEV_ListNodeOfListOfViewer) == AType || TCollection_MapNode::IsKind(AType)); 
//}
//Handle_McCadAEV_ListNodeOfListOfViewer::~Handle_McCadAEV_ListNodeOfListOfViewer() {}
#define Item McCadAEV_Viewer
#define Item_hxx <McCadAEV_Viewer.hxx>
#define TCollection_ListNode McCadAEV_ListNodeOfListOfViewer
#define TCollection_ListNode_hxx <McCadAEV_ListNodeOfListOfViewer.hxx>
#define TCollection_ListIterator McCadAEV_ListIteratorOfListOfViewer
#define TCollection_ListIterator_hxx <McCadAEV_ListIteratorOfListOfViewer.hxx>
#define Handle_TCollection_ListNode Handle_McCadAEV_ListNodeOfListOfViewer
#define TCollection_ListNode_Type_() McCadAEV_ListNodeOfListOfViewer_Type_()
#define TCollection_List McCadAEV_ListOfViewer
#define TCollection_List_hxx <McCadAEV_ListOfViewer.hxx>
#include <TCollection_ListNode.gxx>

