// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadAEV_ListIteratorOfListOfViewerPtr.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _McCadAEV_ListOfViewerPtr_HeaderFile
#include <McCadAEV_ListOfViewerPtr.hxx>
#endif
#ifndef _McCadAEV_ListNodeOfListOfViewerPtr_HeaderFile
#include <McCadAEV_ListNodeOfListOfViewerPtr.hxx>
#endif
 

#define Item McCadAEV_ViewerPtr
#define Item_hxx <McCadAEV_ViewerPtr.hxx>
#define TCollection_ListNode McCadAEV_ListNodeOfListOfViewerPtr
#define TCollection_ListNode_hxx <McCadAEV_ListNodeOfListOfViewerPtr.hxx>
#define TCollection_ListIterator McCadAEV_ListIteratorOfListOfViewerPtr
#define TCollection_ListIterator_hxx <McCadAEV_ListIteratorOfListOfViewerPtr.hxx>
#define Handle_TCollection_ListNode Handle_McCadAEV_ListNodeOfListOfViewerPtr
#define TCollection_ListNode_Type_() McCadAEV_ListNodeOfListOfViewerPtr_Type_()
#define TCollection_List McCadAEV_ListOfViewerPtr
#define TCollection_List_hxx <McCadAEV_ListOfViewerPtr.hxx>
#include <TCollection_ListIterator.gxx>

