// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#include <McCadEXPlug_SequenceOfSharedLibrary.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _OSD_SharedLibrary_HeaderFile
#include <OSD_SharedLibrary.hxx>
#endif
#ifndef _McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary_HeaderFile
#include <McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary.hxx>
#endif
 

#define SeqItem OSD_SharedLibrary
#define SeqItem_hxx <OSD_SharedLibrary.hxx>
#define TCollection_SequenceNode McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary
#define TCollection_SequenceNode_hxx <McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary
#define TCollection_SequenceNode_Type_() McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary_Type_()
#define TCollection_Sequence McCadEXPlug_SequenceOfSharedLibrary
#define TCollection_Sequence_hxx <McCadEXPlug_SequenceOfSharedLibrary.hxx>
#include <TCollection_Sequence.gxx>

