// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_McCadModelManager_HSequenceOfModelParties_HeaderFile
#define _Handle_McCadModelManager_HSequenceOfModelParties_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_MMgt_TShared_HeaderFile
#include <Handle_MMgt_TShared.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(MMgt_TShared);
class McCadModelManager_HSequenceOfModelParties;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(McCadModelManager_HSequenceOfModelParties);

class Handle(McCadModelManager_HSequenceOfModelParties) : public Handle(MMgt_TShared) {
  public:
    Handle(McCadModelManager_HSequenceOfModelParties)():Handle(MMgt_TShared)() {} 
    Handle(McCadModelManager_HSequenceOfModelParties)(const Handle(McCadModelManager_HSequenceOfModelParties)& aHandle) : Handle(MMgt_TShared)(aHandle) 
     {
     }

    Handle(McCadModelManager_HSequenceOfModelParties)(const McCadModelManager_HSequenceOfModelParties* anItem) : Handle(MMgt_TShared)((MMgt_TShared *)anItem) 
     {
     }

    Handle(McCadModelManager_HSequenceOfModelParties)& operator=(const Handle(McCadModelManager_HSequenceOfModelParties)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(McCadModelManager_HSequenceOfModelParties)& operator=(const McCadModelManager_HSequenceOfModelParties* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    McCadModelManager_HSequenceOfModelParties* operator->() const
     {
      return (McCadModelManager_HSequenceOfModelParties *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(McCadModelManager_HSequenceOfModelParties)();
 
   Standard_EXPORT static const Handle(McCadModelManager_HSequenceOfModelParties) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
