// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_McCadMcRead_SequenceNodeOfSequenceOfFill_HeaderFile
#define _Handle_McCadMcRead_SequenceNodeOfSequenceOfFill_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_TCollection_SeqNode_HeaderFile
#include <Handle_TCollection_SeqNode.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(TCollection_SeqNode);
class McCadMcRead_SequenceNodeOfSequenceOfFill;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(McCadMcRead_SequenceNodeOfSequenceOfFill);

class Handle(McCadMcRead_SequenceNodeOfSequenceOfFill) : public Handle(TCollection_SeqNode) {
  public:
    Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)():Handle(TCollection_SeqNode)() {} 
    Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)(const Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)& aHandle) : Handle(TCollection_SeqNode)(aHandle) 
     {
     }

    Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)(const McCadMcRead_SequenceNodeOfSequenceOfFill* anItem) : Handle(TCollection_SeqNode)((TCollection_SeqNode *)anItem) 
     {
     }

    Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)& operator=(const Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)& operator=(const McCadMcRead_SequenceNodeOfSequenceOfFill* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    McCadMcRead_SequenceNodeOfSequenceOfFill* operator->() const
     {
      return (McCadMcRead_SequenceNodeOfSequenceOfFill *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(McCadMcRead_SequenceNodeOfSequenceOfFill)();
 
   Standard_EXPORT static const Handle(McCadMcRead_SequenceNodeOfSequenceOfFill) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
