// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface_HeaderFile
#define _Handle_McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_TCollection_MapNode_HeaderFile
#include <Handle_TCollection_MapNode.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(TCollection_MapNode);
class McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface);

class Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface) : public Handle(TCollection_MapNode) {
  public:
    Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)():Handle(TCollection_MapNode)() {} 
    Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)(const Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)& aHandle) : Handle(TCollection_MapNode)(aHandle) 
     {
     }

    Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)(const McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface* anItem) : Handle(TCollection_MapNode)((TCollection_MapNode *)anItem) 
     {
     }

    Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)& operator=(const Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)& operator=(const McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface* operator->() const
     {
      return (McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface *)ControlAccess();
     }

//   Standard_EXPORT ~Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface)();
 
   Standard_EXPORT static const Handle(McCadCSGGeom_DataMapNodeOfDataMapOfIntegerSurface) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
