// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadDiscDs_SequenceOfSeqOfDiscSolid_HeaderFile
#define _McCadDiscDs_SequenceOfSeqOfDiscSolid_HeaderFile

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid_HeaderFile
#include <Handle_McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class McCadDiscDs_SequenceOfDiscSolid;
class McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadDiscDs_SequenceOfSeqOfDiscSolid  : public TCollection_BaseSequence {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

McCadDiscDs_SequenceOfSeqOfDiscSolid();


Standard_EXPORT   void Clear() ;
~McCadDiscDs_SequenceOfSeqOfDiscSolid()
{
  Clear();
}



Standard_EXPORT  const McCadDiscDs_SequenceOfSeqOfDiscSolid& Assign(const McCadDiscDs_SequenceOfSeqOfDiscSolid& Other) ;
 const McCadDiscDs_SequenceOfSeqOfDiscSolid& operator =(const McCadDiscDs_SequenceOfSeqOfDiscSolid& Other) 
{
  return Assign(Other);
}



Standard_EXPORT   void Append(const McCadDiscDs_SequenceOfDiscSolid& T) ;

  void Append(McCadDiscDs_SequenceOfSeqOfDiscSolid& S) ;


Standard_EXPORT   void Prepend(const McCadDiscDs_SequenceOfDiscSolid& T) ;

  void Prepend(McCadDiscDs_SequenceOfSeqOfDiscSolid& S) ;

  void InsertBefore(const Standard_Integer Index,const McCadDiscDs_SequenceOfDiscSolid& T) ;

  void InsertBefore(const Standard_Integer Index,McCadDiscDs_SequenceOfSeqOfDiscSolid& S) ;


Standard_EXPORT   void InsertAfter(const Standard_Integer Index,const McCadDiscDs_SequenceOfDiscSolid& T) ;

  void InsertAfter(const Standard_Integer Index,McCadDiscDs_SequenceOfSeqOfDiscSolid& S) ;


Standard_EXPORT  const McCadDiscDs_SequenceOfDiscSolid& First() const;


Standard_EXPORT  const McCadDiscDs_SequenceOfDiscSolid& Last() const;

  void Split(const Standard_Integer Index,McCadDiscDs_SequenceOfSeqOfDiscSolid& Sub) ;


Standard_EXPORT  const McCadDiscDs_SequenceOfDiscSolid& Value(const Standard_Integer Index) const;
 const McCadDiscDs_SequenceOfDiscSolid& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}



Standard_EXPORT   void SetValue(const Standard_Integer Index,const McCadDiscDs_SequenceOfDiscSolid& I) ;


Standard_EXPORT   McCadDiscDs_SequenceOfDiscSolid& ChangeValue(const Standard_Integer Index) ;
  McCadDiscDs_SequenceOfDiscSolid& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}



Standard_EXPORT   void Remove(const Standard_Integer Index) ;


Standard_EXPORT   void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


Standard_EXPORT McCadDiscDs_SequenceOfSeqOfDiscSolid(const McCadDiscDs_SequenceOfSeqOfDiscSolid& Other);


 // Fields PRIVATE
 //


};

#define SeqItem McCadDiscDs_SequenceOfDiscSolid
#define SeqItem_hxx <McCadDiscDs_SequenceOfDiscSolid.hxx>
#define TCollection_SequenceNode McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid
#define TCollection_SequenceNode_hxx <McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid
#define TCollection_SequenceNode_Type_() McCadDiscDs_SequenceNodeOfSequenceOfSeqOfDiscSolid_Type_()
#define TCollection_Sequence McCadDiscDs_SequenceOfSeqOfDiscSolid
#define TCollection_Sequence_hxx <McCadDiscDs_SequenceOfSeqOfDiscSolid.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
