// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadCSGAdapt_SolidAnalyser_HeaderFile
#define _McCadCSGAdapt_SolidAnalyser_HeaderFile

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_TopTools_HSequenceOfShape_HeaderFile
#include <Handle_TopTools_HSequenceOfShape.hxx>
#endif
#ifndef _TopoDS_Solid_HeaderFile
#include <TopoDS_Solid.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class TopTools_HSequenceOfShape;
class TopoDS_Solid;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

/** Encapsulation of the OCC shape fixer ShapeFix_Solid*/
class McCadCSGAdapt_SolidAnalyser  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

/** analysis and repair of shapes <br> */
Standard_EXPORT McCadCSGAdapt_SolidAnalyser();

/** ctor with initialization */
Standard_EXPORT McCadCSGAdapt_SolidAnalyser(const TopoDS_Solid& theSolid);

/** initialize values */
Standard_EXPORT   void Init(const TopoDS_Solid& theSolid) ;

/** call Fix() and return fixed solid */
Standard_EXPORT   TopoDS_Solid FixedSolid() ;

/** returns status of fixing state (true/false) */
bool IsFixed();

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


Standard_EXPORT   void Fix() ;


 // Fields PRIVATE
 //
Standard_Boolean myIsFixed;
Standard_Boolean isDecomposed;
Handle_TopTools_HSequenceOfShape myResultSolid;
TopoDS_Solid myFirstSolid;


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
