// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadDiscDs_ListIteratorOfListOfDiscFace_HeaderFile
#define _McCadDiscDs_ListIteratorOfListOfDiscFace_HeaderFile

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_McCadDiscDs_ListNodeOfListOfDiscFace_HeaderFile
#include <Handle_McCadDiscDs_ListNodeOfListOfDiscFace.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class McCadDiscDs_ListOfDiscFace;
class McCadDiscDs_DiscFace;
class McCadDiscDs_ListNodeOfListOfDiscFace;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadDiscDs_ListIteratorOfListOfDiscFace  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 


Standard_EXPORT McCadDiscDs_ListIteratorOfListOfDiscFace();


Standard_EXPORT McCadDiscDs_ListIteratorOfListOfDiscFace(const McCadDiscDs_ListOfDiscFace& L);


Standard_EXPORT   void Initialize(const McCadDiscDs_ListOfDiscFace& L) ;

  Standard_Boolean More() const;


Standard_EXPORT   void Next() ;


Standard_EXPORT   McCadDiscDs_DiscFace& Value() const;


friend class McCadDiscDs_ListOfDiscFace;



protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Standard_Address current;
Standard_Address previous;


};

#define Item McCadDiscDs_DiscFace
#define Item_hxx <McCadDiscDs_DiscFace.hxx>
#define TCollection_ListNode McCadDiscDs_ListNodeOfListOfDiscFace
#define TCollection_ListNode_hxx <McCadDiscDs_ListNodeOfListOfDiscFace.hxx>
#define TCollection_ListIterator McCadDiscDs_ListIteratorOfListOfDiscFace
#define TCollection_ListIterator_hxx <McCadDiscDs_ListIteratorOfListOfDiscFace.hxx>
#define Handle_TCollection_ListNode Handle_McCadDiscDs_ListNodeOfListOfDiscFace
#define TCollection_ListNode_Type_() McCadDiscDs_ListNodeOfListOfDiscFace_Type_()
#define TCollection_List McCadDiscDs_ListOfDiscFace
#define TCollection_List_hxx <McCadDiscDs_ListOfDiscFace.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
