// File generated by CPPExt (Enum)
//
//                     Copyright (C) 1991 - 2000 by
//                      Matra Datavision SA.  All rights reserved.
//
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
//
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadTool_TaskID_HeaderFile
#define _McCadTool_TaskID_HeaderFile


enum McCadTool_TaskID {
 McCadTool_NoID,
McCadTool_Axo,
McCadTool_Axis,
McCadTool_FileNew,
McCadTool_FileOpen,
McCadTool_FileOpenNew,
McCadTool_FileClose,
McCadTool_FileSave,
McCadTool_FileSaveAs,
McCadTool_Hardcopy,
McCadTool_ImportGeom,
McCadTool_ExportGeom,
McCadTool_ExportMCBase,
McCadTool_ImportBREP,
McCadTool_ImportIGES,
McCadTool_ImportSTEP,
McCadTool_ImportMCNP,
McCadTool_ExportBREP,
McCadTool_ExportIGES,
McCadTool_ExportSTEP,
McCadTool_ExportMCNP,
McCadTool_Printer,
McCadTool_PrinterSetup,
McCadTool_PrintPreview,
McCadTool_Print,
McCadTool_ResentFiles,
McCadTool_EditUndo,
McCadTool_EditRedo,
McCadTool_EditCut,
McCadTool_EditCopy,
McCadTool_EditPaste,
McCadTool_Select,
McCadTool_SelectAll,
McCadTool_DeselectAll,
McCadTool_Redraw,
McCadTool_ZoomWindow,
McCadTool_ZoomDynamic,
McCadTool_ZoomIn,
McCadTool_ZoomOut,
McCadTool_FitAll,
McCadTool_Pan,
McCadTool_Grid,
McCadTool_Rotate,
McCadTool_BackProject,
McCadTool_FrontProject,
McCadTool_TopProject,
McCadTool_BottomProject,
McCadTool_LeftProject,
McCadTool_RightProject,
McCadTool_WireFrame,
McCadTool_FlatShade,
McCadTool_MeasureDistance,
McCadTool_MeasureAngle,
McCadTool_MeasureArea,
McCadTool_MeasureVolume,
McCadTool_PropertyCurve,
McCadTool_PropertySurface,
McCadTool_MakeBox,
McCadTool_MakeCone,
McCadTool_MakeCylinder,
McCadTool_MakeHalfSpace,
McCadTool_MakeSphere,
McCadTool_MakeTorus,
McCadTool_MakeWedge,
McCadTool_ModelErase,
McCadTool_ModelCopy,
McCadTool_ModelMirror,
McCadTool_ModelMove,
McCadTool_ModelRotate,
McCadTool_ModelScale,
McCadTool_ModelStrech,
McCadTool_SolidUnion,
McCadTool_SolidIntersection,
McCadTool_SolidDifference,
McCadTool_BackgroundColor,
McCadTool_ShapeColor,
McCadTool_ShapeMaterial,
McCadTool_ShapeTransparency,
McCadTool_Antialiasing,
McCadTool_SetHiddenLine,
McCadTool_DispSelOnly,
McCadTool_ShowAll,
McCadTool_HideSelected,
McCadTool_RedispSelected,
McCadTool_AddToMaterialGroup,
McCadTool_ClippingPlane,
McCadTool_AddMaterialGroup,
McCadTool_ReadValueList
};


#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
