// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadPrsStd_AISInfo_HeaderFile
#define _McCadPrsStd_AISInfo_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadPrsStd_AISInfo_HeaderFile
#include <Handle_McCadPrsStd_AISInfo.hxx>
#endif

#ifndef _Quantity_NameOfColor_HeaderFile
#include <Quantity_NameOfColor.hxx>
#endif
#ifndef _Graphic3d_NameOfMaterial_HeaderFile
#include <Graphic3d_NameOfMaterial.hxx>
#endif
#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
class TCollection_AsciiString;


//! decorates the AIS_InteractiveObject <br>
class McCadPrsStd_AISInfo : public MMgt_TShared {

public:
 // Methods PUBLIC
 // 


Standard_EXPORT McCadPrsStd_AISInfo();


Standard_EXPORT McCadPrsStd_AISInfo(const TCollection_AsciiString& theName);


Standard_EXPORT   Graphic3d_NameOfMaterial Material() const;


Standard_EXPORT   void SetMaterial(const Graphic3d_NameOfMaterial aMatName) ;


Standard_EXPORT   Quantity_NameOfColor Color() const;


Standard_EXPORT   void SetColor(const Quantity_NameOfColor aColor) ;


Standard_EXPORT   TCollection_AsciiString Name() const;


Standard_EXPORT   void SetName(const TCollection_AsciiString& theName) ;


Standard_EXPORT   Standard_Integer Status() const;


Standard_EXPORT   void SetStatus(const Standard_Integer theMode) ;
//Standard_EXPORT ~McCadPrsStd_AISInfo();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Quantity_NameOfColor myColor;
Graphic3d_NameOfMaterial myMaterial;
TCollection_AsciiString myName;
Standard_Integer myStatus;


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
