// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadDiscDs_ListNodeOfListOfDiscSolid_HeaderFile
#define _McCadDiscDs_ListNodeOfListOfDiscSolid_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadDiscDs_ListNodeOfListOfDiscSolid_HeaderFile
#include <Handle_McCadDiscDs_ListNodeOfListOfDiscSolid.hxx>
#endif

#ifndef _McCadDiscDs_DiscSolid_HeaderFile
#include <McCadDiscDs_DiscSolid.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class McCadDiscDs_DiscSolid;
class McCadDiscDs_ListOfDiscSolid;
class McCadDiscDs_ListIteratorOfListOfDiscSolid;



class McCadDiscDs_ListNodeOfListOfDiscSolid : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadDiscDs_ListNodeOfListOfDiscSolid(const McCadDiscDs_DiscSolid& I,const TCollection_MapNodePtr& n);

  McCadDiscDs_DiscSolid& Value() const;
//Standard_EXPORT ~McCadDiscDs_ListNodeOfListOfDiscSolid();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
McCadDiscDs_DiscSolid myValue;


};

#define Item McCadDiscDs_DiscSolid
#define Item_hxx <McCadDiscDs_DiscSolid.hxx>
#define TCollection_ListNode McCadDiscDs_ListNodeOfListOfDiscSolid
#define TCollection_ListNode_hxx <McCadDiscDs_ListNodeOfListOfDiscSolid.hxx>
#define TCollection_ListIterator McCadDiscDs_ListIteratorOfListOfDiscSolid
#define TCollection_ListIterator_hxx <McCadDiscDs_ListIteratorOfListOfDiscSolid.hxx>
#define Handle_TCollection_ListNode Handle_McCadDiscDs_ListNodeOfListOfDiscSolid
#define TCollection_ListNode_Type_() McCadDiscDs_ListNodeOfListOfDiscSolid_Type_()
#define TCollection_List McCadDiscDs_ListOfDiscSolid
#define TCollection_List_hxx <McCadDiscDs_ListOfDiscSolid.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
