// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadTool_ListNodeOfListOfTask_HeaderFile
#define _McCadTool_ListNodeOfListOfTask_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadTool_ListNodeOfListOfTask_HeaderFile
#include <Handle_McCadTool_ListNodeOfListOfTask.hxx>
#endif

#ifndef _Handle_McCadTool_Task_HeaderFile
#include <Handle_McCadTool_Task.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class McCadTool_Task;
class McCadTool_ListOfTask;
class McCadTool_ListIteratorOfListOfTask;



class McCadTool_ListNodeOfListOfTask : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadTool_ListNodeOfListOfTask(const Handle(McCadTool_Task)& I,const TCollection_MapNodePtr& n);

  Handle_McCadTool_Task& Value() const;
//Standard_EXPORT ~McCadTool_ListNodeOfListOfTask();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Handle_McCadTool_Task myValue;


};

#define Item Handle_McCadTool_Task
#define Item_hxx <McCadTool_Task.hxx>
#define TCollection_ListNode McCadTool_ListNodeOfListOfTask
#define TCollection_ListNode_hxx <McCadTool_ListNodeOfListOfTask.hxx>
#define TCollection_ListIterator McCadTool_ListIteratorOfListOfTask
#define TCollection_ListIterator_hxx <McCadTool_ListIteratorOfListOfTask.hxx>
#define Handle_TCollection_ListNode Handle_McCadTool_ListNodeOfListOfTask
#define TCollection_ListNode_Type_() McCadTool_ListNodeOfListOfTask_Type_()
#define TCollection_List McCadTool_ListOfTask
#define TCollection_List_hxx <McCadTool_ListOfTask.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
