// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by
//                      Matra Datavision SA.  All rights reserved.
//
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
//
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadCSGBuild_SequenceOfSolid_HeaderFile
#define _McCadCSGBuild_SequenceOfSolid_HeaderFile

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_McCadCSGBuild_SequenceNodeOfSequenceOfSolid_HeaderFile
#include <Handle_McCadCSGBuild_SequenceNodeOfSequenceOfSolid.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class TopoDS_Solid;
class McCadCSGBuild_SequenceNodeOfSequenceOfSolid;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadCSGBuild_SequenceOfSolid  : public TCollection_BaseSequence {

public:

    void* operator new(size_t,void* anAddress)
      {
        return anAddress;
      }
    void* operator new(size_t size)
      {
        return Standard::Allocate(size);
      }
    void  operator delete(void *anAddress)
      {
        if (anAddress) Standard::Free((Standard_Address&)anAddress);
      }
 // Methods PUBLIC
 //

McCadCSGBuild_SequenceOfSolid();


Standard_EXPORT   void Clear() ;
~McCadCSGBuild_SequenceOfSolid()
{
  Clear();
}



Standard_EXPORT  const McCadCSGBuild_SequenceOfSolid& Assign(const McCadCSGBuild_SequenceOfSolid& Other) ;
 const McCadCSGBuild_SequenceOfSolid& operator =(const McCadCSGBuild_SequenceOfSolid& Other)
{
  return Assign(Other);
}



Standard_EXPORT   void Append(const TopoDS_Solid& T) ;

  void Append(McCadCSGBuild_SequenceOfSolid& S) ;


Standard_EXPORT   void Prepend(const TopoDS_Solid& T) ;

  void Prepend(McCadCSGBuild_SequenceOfSolid& S) ;

  void InsertBefore(const Standard_Integer Index,const TopoDS_Solid& T) ;

  void InsertBefore(const Standard_Integer Index,McCadCSGBuild_SequenceOfSolid& S) ;


Standard_EXPORT   void InsertAfter(const Standard_Integer Index,const TopoDS_Solid& T) ;

  void InsertAfter(const Standard_Integer Index,McCadCSGBuild_SequenceOfSolid& S) ;


Standard_EXPORT  const TopoDS_Solid& First() const;


Standard_EXPORT  const TopoDS_Solid& Last() const;

  void Split(const Standard_Integer Index,McCadCSGBuild_SequenceOfSolid& Sub) ;


Standard_EXPORT  const TopoDS_Solid& Value(const Standard_Integer Index) const;
 const TopoDS_Solid& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}



Standard_EXPORT   void SetValue(const Standard_Integer Index,const TopoDS_Solid& I) ;


Standard_EXPORT   TopoDS_Solid& ChangeValue(const Standard_Integer Index) ;
  TopoDS_Solid& operator()(const Standard_Integer Index)
{
  return ChangeValue(Index);
}



Standard_EXPORT   void Remove(const Standard_Integer Index) ;


Standard_EXPORT   void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:

 // Methods PROTECTED
 //


 // Fields PROTECTED
 //


private:

 // Methods PRIVATE
 //


Standard_EXPORT McCadCSGBuild_SequenceOfSolid(const McCadCSGBuild_SequenceOfSolid& Other);


 // Fields PRIVATE
 //


};

#define SeqItem TopoDS_Solid
#define SeqItem_hxx <TopoDS_Solid.hxx>
#define TCollection_SequenceNode McCadCSGBuild_SequenceNodeOfSequenceOfSolid
#define TCollection_SequenceNode_hxx <McCadCSGBuild_SequenceNodeOfSequenceOfSolid.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadCSGBuild_SequenceNodeOfSequenceOfSolid
#define TCollection_SequenceNode_Type_() McCadCSGBuild_SequenceNodeOfSequenceOfSolid_Type_()
#define TCollection_Sequence McCadCSGBuild_SequenceOfSolid
#define TCollection_Sequence_hxx <McCadCSGBuild_SequenceOfSolid.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
