// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadEXPlug_HeaderFile
#define _McCadEXPlug_HeaderFile

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class OSD_Path;
class McCadEXPlug_PluginManager;
class McCadEXPlug_ExchangePlugin;
class McCadEXPlug_SequenceOfSharedLibrary;
class McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

//! This  package  <McCadEXPlug.cdl> provides <br>
//!          plugable date Import/Export interfaces. <br>
class McCadEXPlug  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

//! Returns TRUE if <thePath> exists. <br>
Standard_EXPORT static  Standard_Boolean PathExists(const OSD_Path& thePath) ;

//! Returns TRUE if <thePath> is radable <br>
Standard_EXPORT static  Standard_Boolean PathIsReadable(const OSD_Path& thePath) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //

friend class McCadEXPlug_PluginManager;
friend class McCadEXPlug_ExchangePlugin;
friend class McCadEXPlug_SequenceOfSharedLibrary;
friend class McCadEXPlug_SequenceNodeOfSequenceOfSharedLibrary;

};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
