// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadModelManager_SequenceOfModelParties_HeaderFile
#define _McCadModelManager_SequenceOfModelParties_HeaderFile

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_McCadModelManager_SequenceNodeOfSequenceOfModelParties_HeaderFile
#include <Handle_McCadModelManager_SequenceNodeOfSequenceOfModelParties.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class McCadModelManager_Part;
class McCadModelManager_SequenceNodeOfSequenceOfModelParties;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadModelManager_SequenceOfModelParties  : public TCollection_BaseSequence {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

McCadModelManager_SequenceOfModelParties();


Standard_EXPORT   void Clear() ;
~McCadModelManager_SequenceOfModelParties()
{
  Clear();
}



Standard_EXPORT  const McCadModelManager_SequenceOfModelParties& Assign(const McCadModelManager_SequenceOfModelParties& Other) ;
 const McCadModelManager_SequenceOfModelParties& operator =(const McCadModelManager_SequenceOfModelParties& Other) 
{
  return Assign(Other);
}



Standard_EXPORT   void Append(const McCadModelManager_Part& T) ;

  void Append(McCadModelManager_SequenceOfModelParties& S) ;


Standard_EXPORT   void Prepend(const McCadModelManager_Part& T) ;

  void Prepend(McCadModelManager_SequenceOfModelParties& S) ;

  void InsertBefore(const Standard_Integer Index,const McCadModelManager_Part& T) ;

  void InsertBefore(const Standard_Integer Index,McCadModelManager_SequenceOfModelParties& S) ;


Standard_EXPORT   void InsertAfter(const Standard_Integer Index,const McCadModelManager_Part& T) ;

  void InsertAfter(const Standard_Integer Index,McCadModelManager_SequenceOfModelParties& S) ;


Standard_EXPORT  const McCadModelManager_Part& First() const;


Standard_EXPORT  const McCadModelManager_Part& Last() const;

  void Split(const Standard_Integer Index,McCadModelManager_SequenceOfModelParties& Sub) ;


Standard_EXPORT  const McCadModelManager_Part& Value(const Standard_Integer Index) const;
 const McCadModelManager_Part& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}



Standard_EXPORT   void SetValue(const Standard_Integer Index,const McCadModelManager_Part& I) ;


Standard_EXPORT   McCadModelManager_Part& ChangeValue(const Standard_Integer Index) ;
  McCadModelManager_Part& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}



Standard_EXPORT   void Remove(const Standard_Integer Index) ;


Standard_EXPORT   void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


Standard_EXPORT McCadModelManager_SequenceOfModelParties(const McCadModelManager_SequenceOfModelParties& Other);


 // Fields PRIVATE
 //


};

#define SeqItem McCadModelManager_Part
#define SeqItem_hxx <McCadModelManager_Part.hxx>
#define TCollection_SequenceNode McCadModelManager_SequenceNodeOfSequenceOfModelParties
#define TCollection_SequenceNode_hxx <McCadModelManager_SequenceNodeOfSequenceOfModelParties.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadModelManager_SequenceNodeOfSequenceOfModelParties
#define TCollection_SequenceNode_Type_() McCadModelManager_SequenceNodeOfSequenceOfModelParties_Type_()
#define TCollection_Sequence McCadModelManager_SequenceOfModelParties
#define TCollection_Sequence_hxx <McCadModelManager_SequenceOfModelParties.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
