// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo_HeaderFile
#define _McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo_HeaderFile
#include <Handle_McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo.hxx>
#endif

#ifndef _Handle_AIS_InteractiveObject_HeaderFile
#include <Handle_AIS_InteractiveObject.hxx>
#endif
#ifndef _Handle_McCadPrsStd_AISInfo_HeaderFile
#include <Handle_McCadPrsStd_AISInfo.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class AIS_InteractiveObject;
class McCadPrsStd_AISInfo;
class TColStd_MapTransientHasher;
class McCadPrsStd_DataMapOfAISWithInfo;
class McCadPrsStd_DataMapIteratorOfDataMapOfAISWithInfo;



class McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo(const Handle(AIS_InteractiveObject)& K,const Handle(McCadPrsStd_AISInfo)& I,const TCollection_MapNodePtr& n);

  Handle_AIS_InteractiveObject& Key() const;

  Handle_McCadPrsStd_AISInfo& Value() const;
//Standard_EXPORT ~McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Handle_AIS_InteractiveObject myKey;
Handle_McCadPrsStd_AISInfo myValue;


};

#define TheKey Handle_AIS_InteractiveObject
#define TheKey_hxx <AIS_InteractiveObject.hxx>
#define TheItem Handle_McCadPrsStd_AISInfo
#define TheItem_hxx <McCadPrsStd_AISInfo.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <TColStd_MapTransientHasher.hxx>
#define TCollection_DataMapNode McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo
#define TCollection_DataMapNode_hxx <McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo.hxx>
#define TCollection_DataMapIterator McCadPrsStd_DataMapIteratorOfDataMapOfAISWithInfo
#define TCollection_DataMapIterator_hxx <McCadPrsStd_DataMapIteratorOfDataMapOfAISWithInfo.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo
#define TCollection_DataMapNode_Type_() McCadPrsStd_DataMapNodeOfDataMapOfAISWithInfo_Type_()
#define TCollection_DataMap McCadPrsStd_DataMapOfAISWithInfo
#define TCollection_DataMap_hxx <McCadPrsStd_DataMapOfAISWithInfo.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
