// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadTool_TaskHistory_HeaderFile
#define _McCadTool_TaskHistory_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadTool_TaskHistory_HeaderFile
#include <Handle_McCadTool_TaskHistory.hxx>
#endif

#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _McCadTool_ListOfTask_HeaderFile
#include <McCadTool_ListOfTask.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Handle_McCadTool_Task_HeaderFile
#include <Handle_McCadTool_Task.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class McCadTool_Task;


//! base Task class <br>
//!   fully implemented this gives a cmd with a finite state machine (FSM) <br>
//!   this is a lazy implementation; see text books for complete cmd with <br>
//!   FSM. <br>
class McCadTool_TaskHistory : public MMgt_TShared {

public:
 // Methods PUBLIC
 // 


Standard_EXPORT McCadTool_TaskHistory(const Standard_Integer theSize = 10);

//! Deletes t<me>. <br>
Standard_EXPORT virtual  void Destroy() ;
~McCadTool_TaskHistory()
{
  Destroy();
}



Standard_EXPORT virtual  void SetSize(const Standard_Integer theSize = 10) ;


Standard_EXPORT virtual  Standard_Integer GetSize() const;


Standard_EXPORT virtual  void Log(const Handle(McCadTool_Task)& theTask) ;


Standard_EXPORT virtual  Standard_Boolean CanUndo() const;


Standard_EXPORT virtual  void Undo() ;


Standard_EXPORT virtual  void Undo(const Standard_Integer theIndex) ;


Standard_EXPORT virtual  Standard_Boolean CanRedo() const;


Standard_EXPORT virtual  void Redo() ;


Standard_EXPORT virtual  void Redo(const Standard_Integer theIndex) ;


Standard_EXPORT virtual  void Clear() ;


Standard_EXPORT virtual  void ClearUndoList() ;


Standard_EXPORT virtual  void ClearRedoList() ;




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //
Standard_Integer mySize;
McCadTool_ListOfTask myUndoList;
McCadTool_ListOfTask myRedoList;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
