// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadCSGTool_Extender_HeaderFile
#define _McCadCSGTool_Extender_HeaderFile

#ifndef _TopoDS_Solid_HeaderFile
#include <TopoDS_Solid.hxx>
#endif
#ifndef _Handle_McCadTDS_ExtSolid_HeaderFile
#include <Handle_McCadTDS_ExtSolid.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class McCadTDS_ExtSolid;
class TopoDS_Solid;

#include <TopTools_HSequenceOfShape.hxx>
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


//! \brief Extends the boundary set of a solid


class McCadCSGTool_Extender  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

//! This class extends a solid by adding resultant faces <br>
//!  whenever necessary. <br>
Standard_EXPORT McCadCSGTool_Extender();


Standard_EXPORT McCadCSGTool_Extender(const TopoDS_Solid& theSolid);


Standard_EXPORT   void Init(const TopoDS_Solid& theSolid) ;


Standard_EXPORT   Standard_Boolean IsDone() const;


Standard_EXPORT   void Done() ;


Standard_EXPORT   void NotDone() ;


Standard_EXPORT   Handle_McCadTDS_ExtSolid ExtSolid() const;


Standard_EXPORT  void FuseFaces(Handle(TopTools_HSequenceOfShape)& fcSeq, Standard_Boolean reversedOnly = Standard_True);



protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
TopoDS_Solid mySolid;
Handle_McCadTDS_ExtSolid myExtSolid;
Standard_Boolean myIsDone;


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
