// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger_HeaderFile
#define _McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger_HeaderFile
#include <Handle_McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger.hxx>
#endif

#ifndef _McCadModelManager_ShapePtr_HeaderFile
#include <McCadModelManager_ShapePtr.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class McCadModelManager_MapShapePtrHasher;
class McCadModelManager_DataMapOfShapePtrInteger;
class McCadModelManager_DataMapIteratorOfDataMapOfShapePtrInteger;



class McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger(const McCadModelManager_ShapePtr& K,const Standard_Integer& I,const TCollection_MapNodePtr& n);

  McCadModelManager_ShapePtr& Key() const;

  Standard_Integer& Value() const;
//Standard_EXPORT ~McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger();




 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
McCadModelManager_ShapePtr myKey;
Standard_Integer myValue;


};

#define TheKey McCadModelManager_ShapePtr
#define TheKey_hxx <McCadModelManager_ShapePtr.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher McCadModelManager_MapShapePtrHasher
#define Hasher_hxx <McCadModelManager_MapShapePtrHasher.hxx>
#define TCollection_DataMapNode McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger
#define TCollection_DataMapNode_hxx <McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger.hxx>
#define TCollection_DataMapIterator McCadModelManager_DataMapIteratorOfDataMapOfShapePtrInteger
#define TCollection_DataMapIterator_hxx <McCadModelManager_DataMapIteratorOfDataMapOfShapePtrInteger.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger
#define TCollection_DataMapNode_Type_() McCadModelManager_DataMapNodeOfDataMapOfShapePtrInteger_Type_()
#define TCollection_DataMap McCadModelManager_DataMapOfShapePtrInteger
#define TCollection_DataMap_hxx <McCadModelManager_DataMapOfShapePtrInteger.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
