// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString_HeaderFile
#define _McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString_HeaderFile
#include <Handle_McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString.hxx>
#endif

#ifndef _TDF_Label_HeaderFile
#include <TDF_Label.hxx>
#endif
#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class TDF_Label;
class TCollection_AsciiString;
class TDF_LabelMapHasher;
class McCadMDReader_DataMapOfLabelAsciiString;
class McCadMDReader_DataMapIteratorOfDataMapOfLabelAsciiString;



class McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString(const TDF_Label& K,const TCollection_AsciiString& I,const TCollection_MapNodePtr& n);

  TDF_Label& Key() const;

  TCollection_AsciiString& Value() const;
//Standard_EXPORT ~McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString();



void* Find1(const Standard_Integer& K) const;
void* ChangeFind1(const Standard_Integer& K) ;

 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
TDF_Label myKey;
TCollection_AsciiString myValue;


};

#define TheKey TDF_Label
#define TheKey_hxx <TDF_Label.hxx>
#define TheItem TCollection_AsciiString
#define TheItem_hxx <TCollection_AsciiString.hxx>
#define Hasher TDF_LabelMapHasher
#define Hasher_hxx <TDF_LabelMapHasher.hxx>
#define TCollection_DataMapNode McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString
#define TCollection_DataMapNode_hxx <McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString.hxx>
#define TCollection_DataMapIterator McCadMDReader_DataMapIteratorOfDataMapOfLabelAsciiString
#define TCollection_DataMapIterator_hxx <McCadMDReader_DataMapIteratorOfDataMapOfLabelAsciiString.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString
#define TCollection_DataMapNode_Type_() McCadMDReader_DataMapNodeOfDataMapOfLabelAsciiString_Type_()
#define TCollection_DataMap McCadMDReader_DataMapOfLabelAsciiString
#define TCollection_DataMap_hxx <McCadMDReader_DataMapOfLabelAsciiString.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
