// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadTDS_SequenceOfExtSolid_HeaderFile
#define _McCadTDS_SequenceOfExtSolid_HeaderFile

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_McCadTDS_ExtSolid_HeaderFile
#include <Handle_McCadTDS_ExtSolid.hxx>
#endif
#ifndef _Handle_McCadTDS_SequenceNodeOfSequenceOfExtSolid_HeaderFile
#include <Handle_McCadTDS_SequenceNodeOfSequenceOfExtSolid.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class McCadTDS_ExtSolid;
class McCadTDS_SequenceNodeOfSequenceOfExtSolid;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadTDS_SequenceOfExtSolid  : public TCollection_BaseSequence {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

McCadTDS_SequenceOfExtSolid();


Standard_EXPORT   void Clear() ;
~McCadTDS_SequenceOfExtSolid()
{
  Clear();
}



Standard_EXPORT  const McCadTDS_SequenceOfExtSolid& Assign(const McCadTDS_SequenceOfExtSolid& Other) ;
 const McCadTDS_SequenceOfExtSolid& operator =(const McCadTDS_SequenceOfExtSolid& Other) 
{
  return Assign(Other);
}



Standard_EXPORT   void Append(const Handle(McCadTDS_ExtSolid)& T) ;

  void Append(McCadTDS_SequenceOfExtSolid& S) ;


Standard_EXPORT   void Prepend(const Handle(McCadTDS_ExtSolid)& T) ;

  void Prepend(McCadTDS_SequenceOfExtSolid& S) ;

  void InsertBefore(const Standard_Integer Index,const Handle(McCadTDS_ExtSolid)& T) ;

  void InsertBefore(const Standard_Integer Index,McCadTDS_SequenceOfExtSolid& S) ;


Standard_EXPORT   void InsertAfter(const Standard_Integer Index,const Handle(McCadTDS_ExtSolid)& T) ;

  void InsertAfter(const Standard_Integer Index,McCadTDS_SequenceOfExtSolid& S) ;


Standard_EXPORT  const Handle_McCadTDS_ExtSolid& First() const;


Standard_EXPORT  const Handle_McCadTDS_ExtSolid& Last() const;

  void Split(const Standard_Integer Index,McCadTDS_SequenceOfExtSolid& Sub) ;


Standard_EXPORT  const Handle_McCadTDS_ExtSolid& Value(const Standard_Integer Index) const;
 const Handle_McCadTDS_ExtSolid& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}



Standard_EXPORT   void SetValue(const Standard_Integer Index,const Handle(McCadTDS_ExtSolid)& I) ;


Standard_EXPORT   Handle_McCadTDS_ExtSolid& ChangeValue(const Standard_Integer Index) ;
  Handle_McCadTDS_ExtSolid& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}



Standard_EXPORT   void Remove(const Standard_Integer Index) ;


Standard_EXPORT   void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


Standard_EXPORT McCadTDS_SequenceOfExtSolid(const McCadTDS_SequenceOfExtSolid& Other);


 // Fields PRIVATE
 //


};

#define SeqItem Handle_McCadTDS_ExtSolid
#define SeqItem_hxx <McCadTDS_ExtSolid.hxx>
#define TCollection_SequenceNode McCadTDS_SequenceNodeOfSequenceOfExtSolid
#define TCollection_SequenceNode_hxx <McCadTDS_SequenceNodeOfSequenceOfExtSolid.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadTDS_SequenceNodeOfSequenceOfExtSolid
#define TCollection_SequenceNode_Type_() McCadTDS_SequenceNodeOfSequenceOfExtSolid_Type_()
#define TCollection_Sequence McCadTDS_SequenceOfExtSolid
#define TCollection_Sequence_hxx <McCadTDS_SequenceOfExtSolid.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
