// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadAEV_ListIteratorOfListOfViewer_HeaderFile
#define _McCadAEV_ListIteratorOfListOfViewer_HeaderFile

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_McCadAEV_ListNodeOfListOfViewer_HeaderFile
#include <Handle_McCadAEV_ListNodeOfListOfViewer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class McCadAEV_ListOfViewer;
class McCadAEV_Viewer;
class McCadAEV_ListNodeOfListOfViewer;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadAEV_ListIteratorOfListOfViewer  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 


Standard_EXPORT McCadAEV_ListIteratorOfListOfViewer();


Standard_EXPORT McCadAEV_ListIteratorOfListOfViewer(const McCadAEV_ListOfViewer& L);


Standard_EXPORT   void Initialize(const McCadAEV_ListOfViewer& L) ;

  Standard_Boolean More() const;


Standard_EXPORT   void Next() ;


Standard_EXPORT   McCadAEV_Viewer& Value() const;


friend class McCadAEV_ListOfViewer;



protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Standard_Address current;
Standard_Address previous;


};

#define Item McCadAEV_Viewer
#define Item_hxx <McCadAEV_Viewer.hxx>
#define TCollection_ListNode McCadAEV_ListNodeOfListOfViewer
#define TCollection_ListNode_hxx <McCadAEV_ListNodeOfListOfViewer.hxx>
#define TCollection_ListIterator McCadAEV_ListIteratorOfListOfViewer
#define TCollection_ListIterator_hxx <McCadAEV_ListIteratorOfListOfViewer.hxx>
#define Handle_TCollection_ListNode Handle_McCadAEV_ListNodeOfListOfViewer
#define TCollection_ListNode_Type_() McCadAEV_ListNodeOfListOfViewer_Type_()
#define TCollection_List McCadAEV_ListOfViewer
#define TCollection_List_hxx <McCadAEV_ListOfViewer.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
