// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadCom_SequenceOfDocument_HeaderFile
#define _McCadCom_SequenceOfDocument_HeaderFile

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_McCadCom_Document_HeaderFile
#include <Handle_McCadCom_Document.hxx>
#endif
#ifndef _Handle_McCadCom_SequenceNodeOfSequenceOfDocument_HeaderFile
#include <Handle_McCadCom_SequenceNodeOfSequenceOfDocument.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class McCadCom_Document;
class McCadCom_SequenceNodeOfSequenceOfDocument;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif


class McCadCom_SequenceOfDocument  : public TCollection_BaseSequence {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

McCadCom_SequenceOfDocument();


Standard_EXPORT   void Clear() ;
~McCadCom_SequenceOfDocument()
{
  Clear();
}



Standard_EXPORT  const McCadCom_SequenceOfDocument& Assign(const McCadCom_SequenceOfDocument& Other) ;
 const McCadCom_SequenceOfDocument& operator =(const McCadCom_SequenceOfDocument& Other) 
{
  return Assign(Other);
}



Standard_EXPORT   void Append(const Handle(McCadCom_Document)& T) ;

  void Append(McCadCom_SequenceOfDocument& S) ;


Standard_EXPORT   void Prepend(const Handle(McCadCom_Document)& T) ;

  void Prepend(McCadCom_SequenceOfDocument& S) ;

  void InsertBefore(const Standard_Integer Index,const Handle(McCadCom_Document)& T) ;

  void InsertBefore(const Standard_Integer Index,McCadCom_SequenceOfDocument& S) ;


Standard_EXPORT   void InsertAfter(const Standard_Integer Index,const Handle(McCadCom_Document)& T) ;

  void InsertAfter(const Standard_Integer Index,McCadCom_SequenceOfDocument& S) ;


Standard_EXPORT  const Handle_McCadCom_Document& First() const;


Standard_EXPORT  const Handle_McCadCom_Document& Last() const;

  void Split(const Standard_Integer Index,McCadCom_SequenceOfDocument& Sub) ;


Standard_EXPORT  const Handle_McCadCom_Document& Value(const Standard_Integer Index) const;
 const Handle_McCadCom_Document& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}



Standard_EXPORT   void SetValue(const Standard_Integer Index,const Handle(McCadCom_Document)& I) ;


Standard_EXPORT   Handle_McCadCom_Document& ChangeValue(const Standard_Integer Index) ;
  Handle_McCadCom_Document& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}



Standard_EXPORT   void Remove(const Standard_Integer Index) ;


Standard_EXPORT   void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


Standard_EXPORT McCadCom_SequenceOfDocument(const McCadCom_SequenceOfDocument& Other);


 // Fields PRIVATE
 //


};

#define SeqItem Handle_McCadCom_Document
#define SeqItem_hxx <McCadCom_Document.hxx>
#define TCollection_SequenceNode McCadCom_SequenceNodeOfSequenceOfDocument
#define TCollection_SequenceNode_hxx <McCadCom_SequenceNodeOfSequenceOfDocument.hxx>
#define Handle_TCollection_SequenceNode Handle_McCadCom_SequenceNodeOfSequenceOfDocument
#define TCollection_SequenceNode_Type_() McCadCom_SequenceNodeOfSequenceOfDocument_Type_()
#define TCollection_Sequence McCadCom_SequenceOfDocument
#define TCollection_Sequence_hxx <McCadCom_SequenceOfDocument.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
