// File generated by CPPExt (Value)
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadCSGTool_HeaderFile
#define _McCadCSGTool_HeaderFile

#ifndef _Handle_TopTools_HSequenceOfShape_HeaderFile
#include <Handle_TopTools_HSequenceOfShape.hxx>
#endif
#ifndef _Handle_TColgp_HSequenceOfPnt_HeaderFile
#include <Handle_TColgp_HSequenceOfPnt.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif

class TopTools_HSequenceOfShape;
class TopoDS_Face;
class TColgp_HSequenceOfPnt;
class TopoDS_Shape;
class TopoDS_Solid;
class McCadCSGTool_CellBuilder;
class McCadCSGTool_Decomposer;
class McCadCSGTool_Extender;
class McCadCSGTool_Cutter;
class McCadCSGTool_TrivialCheck;
class McCadCSGTool_SignCheck;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

//! \brief Collection of useful CSG Tools

//! Implementation of useful Tools for Constructive Solid Geometries. <br>

class McCadCSGTool  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 

//! returns non-redundant points from vertices and all points from face triangulation <br>
//!        used for sign computation; <br>
Standard_EXPORT static  Handle_TColgp_HSequenceOfPnt AllSamplePoints(const TopoDS_Shape& theShape) ;

/*
//! computes resultants using BBox method. <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape AppBoxResultants(const TopoDS_Face& theFace) ;*/

//! computes resultants using BBox method. <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape BoxResultants(const TopoDS_Face& theFace) ;

//! computes partial drivatives <br>
//!  temporary implementation only for conical surfaces!!!! <br>
Standard_EXPORT static Handle_TopTools_HSequenceOfShape Partials(const TopoDS_Face& theFace) ;

Standard_EXPORT static Standard_Boolean GenAuxFaceOfTorus(Handle(TopTools_HSequenceOfShape) & seqResultant,
                                                          const TopoDS_Face & aFace);

Standard_EXPORT static Standard_Boolean AddAuxSurf(const TopoDS_Face& aFace,
                                                   Handle(TopTools_HSequenceOfShape) & seqResultant);

Standard_EXPORT static Standard_Boolean GenAuxFaceOfCylinder(Handle(TopTools_HSequenceOfShape) & seqResultant,
                                                             const TopoDS_Face& aFace);

//! returns non-redundant points from vertices and non-free nodes from <br>
//!        face triangulation. <br>
//!        used for sign computation; <br>
Standard_EXPORT static  Handle_TColgp_HSequenceOfPnt SamplePoints(const TopoDS_Shape& theShape) ;

//! returns non-redundant sample points computed around a face. <br>
//! The method used here is scale transformation. <br>
Standard_EXPORT static  Handle_TColgp_HSequenceOfPnt FaceSamplePoints(const TopoDS_Face& theFace,const Standard_Integer MAXNUMPNT,const Standard_Integer MINNUMPNT) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedLinFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedCylFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedConFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedSphFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedTorFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

//! deletes redundant  faces from the sequence <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape DeleteRedSORFace(Handle_TopTools_HSequenceOfShape& aFaceSeq) ;

/*
//! Linearizing small faces of a solid <br>
//!          in odrder to make Boolean evaluation easy and reduce model comlexity. <br>
Standard_EXPORT static  TopoDS_Solid LinSolid(const TopoDS_Solid& aSolid) ;*/

//! computes resultants using BBox method. <br>
//! <br>
Standard_EXPORT static  Handle_TopTools_HSequenceOfShape Resultants(const TopoDS_Face& theFace) ;



protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //

friend class McCadCSGTool_CellBuilder;
friend class McCadCSGTool_Decomposer;
friend class McCadCSGTool_Extender;
friend class McCadCSGTool_Cutter;
friend class McCadCSGTool_TrivialCheck;
friend class McCadCSGTool_SignCheck;

};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
