// File generated by CPPExt (Transient)
//
//
//                     Copyright (C) 1991 - 2000 by  
//                      Matra Datavision SA.  All rights reserved.
//  
//                     Copyright (C) 2001 - 2004 by
//                     Open CASCADE SA.  All rights reserved.
// 
// This file is part of the Open CASCADE Technology software.
//
// This software may be distributed and/or modified under the terms and
// conditions of the Open CASCADE Public License as defined by Open CASCADE SA
// and appearing in the file LICENSE included in the packaging of this file.
//  
// This software is distributed on an "AS IS" basis, without warranty of any
// kind, and Open CASCADE SA hereby disclaims all such warranties,
// including without limitation, any warranties of merchantability, fitness
// for a particular purpose or non-infringement. Please see the License for
// the specific terms and conditions governing rights and limitations under the
// License.

#ifndef _McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_HeaderFile
#define _McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_HeaderFile
#include <Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill.hxx>
#endif

#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_McCadMcRead_Fill_HeaderFile
#include <Handle_McCadMcRead_Fill.hxx>
#endif
#ifndef _TCollection_MapNode_HeaderFile
#include <TCollection_MapNode.hxx>
#endif
#ifndef _TCollection_MapNodePtr_HeaderFile
#include <TCollection_MapNodePtr.hxx>
#endif
class McCadMcRead_Fill;
class TColStd_MapIntegerHasher;
class McCadMcRead_DataMapOfIntegerFill;
class McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill;



class McCadMcRead_DataMapNodeOfDataMapOfIntegerFill : public TCollection_MapNode {

public:
 // Methods PUBLIC
 // 

McCadMcRead_DataMapNodeOfDataMapOfIntegerFill(const Standard_Integer& K,const Handle(McCadMcRead_Fill)& I,const TCollection_MapNodePtr& n);

  Standard_Integer& Key() const;

  Handle_McCadMcRead_Fill& Value() const;
//Standard_EXPORT ~McCadMcRead_DataMapNodeOfDataMapOfIntegerFill();

void* Find1(const Standard_Integer& K) const;
void* ChangeFind1(const Standard_Integer& K) ;


 // Type management
 //
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 //Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Standard_Integer myKey;
Handle_McCadMcRead_Fill myValue;


};

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_McCadMcRead_Fill
#define TheItem_hxx <McCadMcRead_Fill.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode McCadMcRead_DataMapNodeOfDataMapOfIntegerFill
#define TCollection_DataMapNode_hxx <McCadMcRead_DataMapNodeOfDataMapOfIntegerFill.hxx>
#define TCollection_DataMapIterator McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill
#define TCollection_DataMapIterator_hxx <McCadMcRead_DataMapIteratorOfDataMapOfIntegerFill.hxx>
#define Handle_TCollection_DataMapNode Handle_McCadMcRead_DataMapNodeOfDataMapOfIntegerFill
#define TCollection_DataMapNode_Type_() McCadMcRead_DataMapNodeOfDataMapOfIntegerFill_Type_()
#define TCollection_DataMap McCadMcRead_DataMapOfIntegerFill
#define TCollection_DataMap_hxx <McCadMcRead_DataMapOfIntegerFill.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx


// other Inline functions and methods (like "C++: function call" methods)
//


#endif
